using Pkg
using Pkg; Pkg.status()
Pkg.add("CSV")
Pkg.add("DataFrames")
Pkg.add("DataFrameMacros")
Pkg.add("Chain")
Pkg.add("TimeZones")
Pkg.add("Pipe")
Pkg.add("StatsBase")
Pkg.add("DecisionTree")
Pkg.add(PackageSpec(name="CategoricalArrays", version="0.10.8"))
Pkg.add("JLD2")